all:
	pdflatex Ackerman.tex
	pdflatex Altwaijry.tex
	pdflatex Apthorpe.tex
	pdflatex Ashmore.tex
	pdflatex Bullins.tex
	pdflatex Chaturapruek.tex
	pdflatex Croman.tex
	pdflatex Cui.tex
	pdflatex Foster.tex
	pdflatex Frink.tex
	pdflatex Greenman.tex
	pdflatex Gupta.tex
	pdflatex Hessel.tex
	pdflatex Izatt.tex
	pdflatex Kaspar.tex
	pdflatex Koenig.tex
	pdflatex Konomis.tex
	pdflatex Kumar.tex
	pdflatex Lei.tex
	pdflatex Liu.tex
	pdflatex Maithreyi.tex
	pdflatex Mehne.tex
	pdflatex Meyerson.tex
	pdflatex Miao.tex
	pdflatex Moghimi.tex
	pdflatex Mota.tex
	pdflatex Muzny.tex
	pdflatex Newcomb.tex
	pdflatex Okeke.tex
	pdflatex Pacchiano.tex
	pdflatex schedule_template.tex
	pdflatex Schild.tex
	pdflatex Schofield.tex
	pdflatex Seita.tex
	pdflatex Stubbs.tex
	pdflatex Suksumpong.tex
	pdflatex Townshend.tex
	pdflatex Van.tex
	pdflatex Veit.tex
	pdflatex Wang.tex
	pdflatex Wu.tex
